 services:
   enset-ebank-discovery-service:
     build: ./discovery-service
     container_name: enset-ebank-discovery-service
     ports:
       - '8761:8761'
     expose:
       - '8761'
     healthcheck:
       test: ["CMD","curl","-f","http://localhost:8761/actuator/health"]
       interval: 10s
   enset-ebank-config-service:
     build: ./config-service
     container_name: enset-ebank-config-service
     ports:
       - '9999:9999'
     expose:
       - '9999'
     environment:
       - DISCOVERY_SERVICE_URL=http://enset-ebank-discovery-service:8761/eureka
     healthcheck:
       test: [ "CMD","curl","-f","http://localhost:8761/actuator/health" ]
       interval: 10s
       retries: 5
     depends_on:
       enset-ebank-discovery-service:
         condition: service_healthy
   enset-ebank-customer-service:
     build: ./customer-service
     container_name: enset-ebank-customer-service
     ports:
       - '8090:8090'
     expose:
       - '8090'
     environment:
       - CONFIG_SERVICE_URL=http://enset-ebank-config-service:9999
     depends_on:
       enset-ebank-config-service:
         condition: service_healthy





